#!/bin/sh
#
# tcpsrv
#
[ -f $CFGD/netcfg ] && . $CFGD/netcfg
[ -f /var/udhcpc.lease ] && . /var/udhcpc.lease

case "$1" in
start|2|3|4)
    echo "Set date && start logging."
    [ ! -z "$timesvr" ] && rdate -s $timesvr
    [ ! -z "$logsvr" ] && syslogd -R $logsvr && klogd
    ;;
stop|0|1|6)
    [ ! -z "$logsvr" ] && killall klogd syslogd
    sleep 2
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac
exit 0
