#!/bin/sh
#
# dhcpd
#
if [ ! -f $CFGD/udhcpd.conf ]
then
    echo "No udhcpd configuration aborting script"
    exit 0
fi
if grep "enable *no" $CFGD/udhcpd.conf
then
    echo "udhcpd disabled"
    exit 0
fi
case "$1" in
start|2|3|4)
    set `grep lease_file $CFGD/udhcpd.conf`
    [ ! -f $2 ] && > $2
    udhcpd $CFGD/udhcpd.conf
    ;;
stop|0|1|6)
    killall udhcpd
    sleep 2
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac
